server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/signup
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - WebAuthorizationHeaderFilter
        - id: team-service
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/team-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/team-service/(?<segment>.*), /$\{segment}
            - WebAuthorizationHeaderFilter
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
            - WebAuthorizationHeaderFilter
        - id: web-server
          uri: lb://WEB-SERVER
          predicates:
            - Path=/jobcho/users/login
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/jobcho/(?<segment>.*), /$\{segment}
        - id: web-server
          uri: lb://WEB-SERVER
          predicates:
            - Path=/jobcho/users/register
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/jobcho/(?<segment>.*), /$\{segment}
        - id: web-server
          uri: lb://WEB-SERVER
          predicates:
            - Path=/jobcho/*/*.js
            - Method=GET
          filters:
            - RewritePath=/jobcho/(?<segment>.*), /$\{segment}
        - id: web-server
          uri: lb://WEB-SERVER
          predicates:
            - Path=/jobcho/*/*.css
            - Method=GET
          filters:
            - RewritePath=/jobcho/(?<segment>.*), /$\{segment}
        - id: web-server
          uri: lb://WEB-SERVER
          predicates:
            - Path=/jobcho/*/*/*.js
            - Method=GET
          filters:
            - RewritePath=/jobcho/(?<segment>.*), /$\{segment}
        - id: web-server
          uri: lb://WEB-SERVER
          predicates:
            - Path=/jobcho/*/*/*.css
            - Method=GET
          filters:
            - RewritePath=/jobcho/(?<segment>.*), /$\{segment}
        - id: web-server
          uri: lb://WEB-SERVER
          predicates:
            - Path=/jobcho/**
            - Method=GET
          filters:
            - RewritePath=/jobcho/(?<segment>.*), /$\{segment}
            - WebAuthorizationHeaderFilter
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post-service/**
            - Method=GET, POST, PUT, DELETE
          filters:
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
            - WebAuthorizationHeaderFilter
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board-service/**
            - Method=GET, POST, PUT, DELETE
          filters:
            - RewritePath=/board-service/(?<segment>.*), /$\{segment}
            - WebAuthorizationHeaderFilter
        - id: reply-service
          uri: lb://REPLY-SERVICE
          predicates:
            - Path=/reply-service/**
            - Method=GET, POST, PUT, DELETE
          filters:
            - RewritePath=/reply-service/(?<segment>.*), /$\{segment}
            - WebAuthorizationHeaderFilter
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/**
            - Method=GET, POST, PUT, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}
        - id: chat-service-socket
          uri: lb:ws://chat-service
          predicates:
            - Path=/websocket/**

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace
token:
  expiration_time: 86400000
  secret: user_token